services:
  proof-server:
    image: midnightnetwork/proof-server:4.0.0
    container_name: midnight-proof-server
    environment:
      - RUST_LOG=info
    ports:
      - "6300:6300"
    command: "'midnight-proof-server --network testnet'"
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", ":> /dev/tcp/127.0.0.1/6300 || exit 1"]
    restart: unless-stopped

  wallet-server:
    build:
      context: ../..  # Adjust this path to your Dockerfile location
      dockerfile: Dockerfile
    container_name: midnight-wallet-server-${AGENT_ID:-default}
    environment:
      - AGENT_ID=${AGENT_ID}
      - WALLET_SERVER_HOST=wallet-server
      - WALLET_SERVER_PORT=${WALLET_SERVER_PORT:-3000}
      - NETWORK_ID=TestNet
      - USE_EXTERNAL_PROOF_SERVER=true
      - PROOF_SERVER=http://proof-server:6300
      - INDEXER=https://indexer.testnet-02.midnight.network/api/v1/graphql
      - INDEXER_WS=wss://indexer.testnet-02.midnight.network/api/v1/graphql/ws
      - MN_NODE=https://rpc.testnet-02.midnight.network
      - LOG_LEVEL=info
      - STORAGE_BASE_DIR=/app/.storage
    ports:
      - "${WALLET_SERVER_PORT:-3000}:3000"
    volumes:
      - ./data:/app/.storage
      - ./logs:/app/logs
    depends_on:
      - proof-server
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
